services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"       # Vite dev server
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      POLLING_INTERVAL: "200"
      UV_USE_IO_URING: "0"
    init: true
    tty: true
    command: ["sh", "-lc", "sleep infinity"]

volumes:
  node_modules: {}